# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/minghan/lane-detection/5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/minghan/lane-detection/5

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/minghan/lane-detection/5/CMakeFiles /home/minghan/lane-detection/5/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/minghan/lane-detection/5/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lane-detection

# Build rule for target.
lane-detection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lane-detection
.PHONY : lane-detection

# fast build rule for target.
lane-detection/fast:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/build
.PHONY : lane-detection/fast

#=============================================================================
# Target rules for targets named alglib

# Build rule for target.
alglib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 alglib
.PHONY : alglib

# fast build rule for target.
alglib/fast:
	$(MAKE) -f alglib/CMakeFiles/alglib.dir/build.make alglib/CMakeFiles/alglib.dir/build
.PHONY : alglib/fast

LaneImage.o: LaneImage.cpp.o

.PHONY : LaneImage.o

# target to build an object file
LaneImage.cpp.o:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneImage.cpp.o
.PHONY : LaneImage.cpp.o

LaneImage.i: LaneImage.cpp.i

.PHONY : LaneImage.i

# target to preprocess a source file
LaneImage.cpp.i:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneImage.cpp.i
.PHONY : LaneImage.cpp.i

LaneImage.s: LaneImage.cpp.s

.PHONY : LaneImage.s

# target to generate assembly for a file
LaneImage.cpp.s:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneImage.cpp.s
.PHONY : LaneImage.cpp.s

LaneImage_fit.o: LaneImage_fit.cpp.o

.PHONY : LaneImage_fit.o

# target to build an object file
LaneImage_fit.cpp.o:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneImage_fit.cpp.o
.PHONY : LaneImage_fit.cpp.o

LaneImage_fit.i: LaneImage_fit.cpp.i

.PHONY : LaneImage_fit.i

# target to preprocess a source file
LaneImage_fit.cpp.i:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneImage_fit.cpp.i
.PHONY : LaneImage_fit.cpp.i

LaneImage_fit.s: LaneImage_fit.cpp.s

.PHONY : LaneImage_fit.s

# target to generate assembly for a file
LaneImage_fit.cpp.s:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneImage_fit.cpp.s
.PHONY : LaneImage_fit.cpp.s

LaneImage_p0.o: LaneImage_p0.cpp.o

.PHONY : LaneImage_p0.o

# target to build an object file
LaneImage_p0.cpp.o:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneImage_p0.cpp.o
.PHONY : LaneImage_p0.cpp.o

LaneImage_p0.i: LaneImage_p0.cpp.i

.PHONY : LaneImage_p0.i

# target to preprocess a source file
LaneImage_p0.cpp.i:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneImage_p0.cpp.i
.PHONY : LaneImage_p0.cpp.i

LaneImage_p0.s: LaneImage_p0.cpp.s

.PHONY : LaneImage_p0.s

# target to generate assembly for a file
LaneImage_p0.cpp.s:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneImage_p0.cpp.s
.PHONY : LaneImage_p0.cpp.s

LaneImage_pp.o: LaneImage_pp.cpp.o

.PHONY : LaneImage_pp.o

# target to build an object file
LaneImage_pp.cpp.o:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneImage_pp.cpp.o
.PHONY : LaneImage_pp.cpp.o

LaneImage_pp.i: LaneImage_pp.cpp.i

.PHONY : LaneImage_pp.i

# target to preprocess a source file
LaneImage_pp.cpp.i:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneImage_pp.cpp.i
.PHONY : LaneImage_pp.cpp.i

LaneImage_pp.s: LaneImage_pp.cpp.s

.PHONY : LaneImage_pp.s

# target to generate assembly for a file
LaneImage_pp.cpp.s:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneImage_pp.cpp.s
.PHONY : LaneImage_pp.cpp.s

LaneMark.o: LaneMark.cpp.o

.PHONY : LaneMark.o

# target to build an object file
LaneMark.cpp.o:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneMark.cpp.o
.PHONY : LaneMark.cpp.o

LaneMark.i: LaneMark.cpp.i

.PHONY : LaneMark.i

# target to preprocess a source file
LaneMark.cpp.i:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneMark.cpp.i
.PHONY : LaneMark.cpp.i

LaneMark.s: LaneMark.cpp.s

.PHONY : LaneMark.s

# target to generate assembly for a file
LaneMark.cpp.s:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LaneMark.cpp.s
.PHONY : LaneMark.cpp.s

LearnModel.o: LearnModel.cpp.o

.PHONY : LearnModel.o

# target to build an object file
LearnModel.cpp.o:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LearnModel.cpp.o
.PHONY : LearnModel.cpp.o

LearnModel.i: LearnModel.cpp.i

.PHONY : LearnModel.i

# target to preprocess a source file
LearnModel.cpp.i:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LearnModel.cpp.i
.PHONY : LearnModel.cpp.i

LearnModel.s: LearnModel.cpp.s

.PHONY : LearnModel.s

# target to generate assembly for a file
LearnModel.cpp.s:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/LearnModel.cpp.s
.PHONY : LearnModel.cpp.s

Line.o: Line.cpp.o

.PHONY : Line.o

# target to build an object file
Line.cpp.o:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/Line.cpp.o
.PHONY : Line.cpp.o

Line.i: Line.cpp.i

.PHONY : Line.i

# target to preprocess a source file
Line.cpp.i:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/Line.cpp.i
.PHONY : Line.cpp.i

Line.s: Line.cpp.s

.PHONY : Line.s

# target to generate assembly for a file
Line.cpp.s:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/Line.cpp.s
.PHONY : Line.cpp.s

VanPt.o: VanPt.cpp.o

.PHONY : VanPt.o

# target to build an object file
VanPt.cpp.o:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/VanPt.cpp.o
.PHONY : VanPt.cpp.o

VanPt.i: VanPt.cpp.i

.PHONY : VanPt.i

# target to preprocess a source file
VanPt.cpp.i:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/VanPt.cpp.i
.PHONY : VanPt.cpp.i

VanPt.s: VanPt.cpp.s

.PHONY : VanPt.s

# target to generate assembly for a file
VanPt.cpp.s:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/VanPt.cpp.s
.PHONY : VanPt.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/lane-detection.dir/build.make CMakeFiles/lane-detection.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lane-detection"
	@echo "... alglib"
	@echo "... LaneImage.o"
	@echo "... LaneImage.i"
	@echo "... LaneImage.s"
	@echo "... LaneImage_fit.o"
	@echo "... LaneImage_fit.i"
	@echo "... LaneImage_fit.s"
	@echo "... LaneImage_p0.o"
	@echo "... LaneImage_p0.i"
	@echo "... LaneImage_p0.s"
	@echo "... LaneImage_pp.o"
	@echo "... LaneImage_pp.i"
	@echo "... LaneImage_pp.s"
	@echo "... LaneMark.o"
	@echo "... LaneMark.i"
	@echo "... LaneMark.s"
	@echo "... LearnModel.o"
	@echo "... LearnModel.i"
	@echo "... LearnModel.s"
	@echo "... Line.o"
	@echo "... Line.i"
	@echo "... Line.s"
	@echo "... VanPt.o"
	@echo "... VanPt.i"
	@echo "... VanPt.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

